body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: What is the benefit of the feature, and what problem(s) does it solve? Please include examples.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Design and Implementation
      description: Explain in detail:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Rationale
      description: Explain your design decisions:
    validations:
      required: true
 - type: textarea
    attributes:
      label: Drawbacks
      description: Why **shouldn't** this feature be added
    validations:
      required: true
- type: textarea
    attributes:
      label: Unanswered Questions
      description: (Optional) Gaps in your design that you are unsure of.
    validations:
      required: false
- type: textarea
    attributes:
      label: Future Additions
      description: (Optional) Out-of-scope additions to the feature that could be expanded upon in a future proposal.
    validations:
      required: false
